# Generated by Django 4.2.6 on 2023-10-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classroom", "0005_alter_classroom_code"),
        ("base", "0005_alter_secrettoken_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAG",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("classrooms", models.ManyToManyField(to="classroom.classroom")),
                ("students", models.ManyToManyField(to="base.student")),
            ],
        ),
        migrations.CreateModel(
            name="PAG",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("classrooms", models.ManyToManyField(to="classroom.classroom")),
                ("professors", models.ManyToManyField(to="base.professor")),
            ],
        ),
    ]
