# Generated by Django 4.2.6 on 2023-10-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("floor", models.CharField(max_length=20)),
                ("seating_capacity", models.IntegerField(default=0)),
                ("whiteboard_available", models.BooleanField(default=False)),
                ("projector_available", models.BooleanField(default=False)),
                ("blackboard_available", models.BooleanField(default=False)),
                ("building", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="classroom.building")),
            ],
        ),
    ]
