# Generated by Django 4.2.6 on 2023-10-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="ready",
            field=models.BooleanField(default=False),
        ),
    ]
