# Generated by Django 4.2.6 on 2023-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0002_classroom_ready"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="ready",
            field=models.BooleanField(default=True),
        ),
    ]
