# Generated by Django 4.2.6 on 2023-10-30 14:31

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0003_alter_classroom_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="code",
            field=models.CharField(default=base.models.generate_random_code, max_length=6),
        ),
    ]
