# Generated by Django 4.2.6 on 2023-10-30 14:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0004_classroom_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="code",
            field=models.CharField(default=base.models.generate_random_code, max_length=6, unique=True),
        ),
    ]
