# Generated by Django 4.2.6 on 2023-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(default="0f8c97", max_length=6)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("expiry", models.DateTimeField(auto_now_add=True)),
                (
                    "token_type",
                    models.CharField(choices=[("Student", "Student"), ("Professor", "Professor")], max_length=20),
                ),
            ],
        ),
    ]
