# Generated by Django 4.2.6 on 2023-10-25 12:22

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_secrettoken_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secrettoken",
            name="code",
            field=models.CharField(default=base.models.generate_random_code, max_length=6),
        ),
        migrations.AlterField(
            model_name="secrettoken",
            name="expiry",
            field=models.DateTimeField(),
        ),
    ]
