# Generated by Django 4.2.6 on 2023-10-30 10:22

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_secrettoken_code_alter_secrettoken_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secrettoken",
            name="code",
            field=models.CharField(default=base.models.generate_random_code, max_length=6, unique=True),
        ),
    ]
