# Generated by Django 4.2.6 on 2023-10-31 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0005_alter_secrettoken_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("date", models.DateField()),
                (
                    "repeatable",
                    models.CharField(
                        choices=[
                            ("No Repeat", "No Repeat"),
                            ("Repeat only on Weekdays", "Repeat only on Weekdays"),
                            ("Repeat only on Weekends", "Repeat only on Weekends"),
                            ("Repeat Daily", "Repeat Daily"),
                        ]
                    ),
                ),
                ("expiry", models.DateTimeField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bookings",
                        to="base.professor",
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_bookings",
                        to="base.professor",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.student",
                    ),
                ),
            ],
        ),
    ]
