# Generated by Django 4.2.6 on 2023-11-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_secrettoken_code"),
        ("booking", "0002_booking_booked_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="approval_for",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_approver",
                to="base.professor",
            ),
        ),
    ]
