# Generated by Django 4.2.6 on 2023-11-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0005_alter_classroom_code"),
        ("booking", "0003_booking_approval_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="classroom",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="classroom.classroom"
            ),
        ),
    ]
