# Generated by Django 4.2.6 on 2023-11-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_booking_classroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookedDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="date of booking")),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="booked_dates",
            field=models.ManyToManyField(to="booking.bookeddate"),
        ),
    ]
