# Generated by Django 4.2.6 on 2023-11-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_bookeddate_booking_booked_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="repeatable",
            field=models.CharField(
                choices=[
                    ("No Repeat", "No Repeat"),
                    ("Repeat only on Weekdays", "Repeat only on Weekdays"),
                    ("Repeat only on Weekends", "Repeat only on Weekends"),
                    ("Repeat Daily", "Repeat Daily"),
                    ("Weekly", "Weekly"),
                ]
            ),
        ),
    ]
